# Generated by Django 4.1.3 on 2022-11-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_url_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=200)),
                ('product_manufacturer', models.CharField(max_length=30)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.url')),
            ],
        ),
    ]
