# Generated by Django 4.1.3 on 2022-11-08 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cost', models.IntegerField()),
                ('last_update', models.TimeField()),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.url')),
            ],
        ),
    ]
