# Generated by Django 4.1.3 on 2022-11-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_URl', models.CharField(max_length=300)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.url')),
            ],
        ),
    ]
