# Generated by Django 4.1.3 on 2022-11-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_manufacturer_product_name_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
